language: python

python:
  - 3.6

before_install:
  - script/up

script:
  - script/test

after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      script/distribute;
    fi
