language: python

python:
  - 2.7
  - 3.6

before_install:
  # Apparently TF 1.5.0 is broken and crashes on Travis (possibly glibc version?). This can probably be removed at some point.
  - pip install tensorflow==1.4.1
  - script/up

script:
  - script/test

after_success:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" && "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      script/distribute;
    fi
